# Generated by Django 5.2.2 on 2025-06-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceModule',
            new_name='PricingModule',
        ),
    ]
