# Generated by Django 5.2.2 on 2025-06-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_distanceadditionalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMultiplierFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_minute', models.PositiveIntegerField()),
                ('end_minute', models.PositiveIntegerField()),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmf_entries', to='core.pricingmodule')),
            ],
            options={
                'ordering': ['start_minute'],
            },
        ),
    ]
