# Generated by Django 5.2.2 on 2025-06-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timemultiplierfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cycle_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_entries', to='core.pricingmodule')),
            ],
        ),
    ]
