# Generated by Django 5.2.2 on 2025-06-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_waitingcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('waiting_time_minutes', models.PositiveIntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pricingmodule')),
            ],
        ),
    ]
