# Generated by Django 5.2.2 on 2025-06-07 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distanceadditionalprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dap_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distanceadditionalprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dap_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distancebaseprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbp_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distancebaseprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbp_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timemultiplierfactor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmf_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timemultiplierfactor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tmf_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitingcharges',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wc_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitingcharges',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wc_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
