# Generated by Django 5.2.2 on 2025-06-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ride_created_by_ride_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
