# Generated by Django 5.2.2 on 2025-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pricingconfigchangelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='calculated_price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='ride',
            name='dap_ride',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='dbp_ride',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='tmf_ride',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='wc_ride',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
